public class emailsender{


 public static string name;

  public list<contact> emailgenerater(string email,string body,string subject){
  
    
    /**list<messaging.SingleEmailMessage> mlist=new list<messaging.SingleEmailMessage>();
     messaging.SingleEmailMessage m=new  messaging.SingleEmailMessage();
     m.setbody(body);
     
     mlist.add(m);
     
     messaging.sendemail(mlist);**/
     
     
     secondmethd();
      return null;
       
  }


  public void secondmethd(){
  
  
  }





}