public class myclass {


  public string name;
  public integer age;
  public date dob;
  public datetime actualTime;
  public decimal des;
  public datetime currentTime; 
  public date todaydate;
  public boolean eligible;
  public id salesforceid;
  public beer__c mycontact;
  public myclass mm;
  public contact con;
 
   public myclass(){
 
   List<string> names=new list<string>();
   list<integer> ages=new list<integer>();
   list<contact> contacts=new list<contact>();
 
   names.add('shiva');
   names.add('rajesh');
   
   ages.add(1231);
   ages.add(323);
 
 
   }
 



}